### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by priyanshunayan** [ASarchna/DR135_Exponential2.0#3]
![Screenshot_2020-08-03-15-07-25-610_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174632-d3eafe00-d5a3-11ea-924e-9b35a9a8a713.jpg)
![Screenshot_2020-08-03-15-07-16-892_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174638-d6e5ee80-d5a3-11ea-83e5-3898585b004b.jpg)
![Screenshot_2020-08-03-15-06-56-292_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174642-d8171b80-d5a3-11ea-88a2-1ba861861d6b.jpg)
![Screenshot_2020-08-03-15-05-00-768_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174649-da797580-d5a3-11ea-9485-d1b096995af2.jpg)
![Screenshot_2020-08-03-15-03-24-140_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174655-dcdbcf80-d5a3-11ea-9a79-6f2d36788e1d.jpg)
![Screenshot_2020-08-03-15-02-03-701_com google android apps maps](https://user-images.githubusercontent.com/32892545/89174662-df3e2980-d5a3-11ea-9432-67ac0b0a4848.jpg)
![Screenshot_2020-08-03-15-01-44-691_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174681-e2391a00-d5a3-11ea-90ac-5c3837fc0173.jpg)
![Screenshot_2020-08-03-15-00-37-726_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174684-e49b7400-d5a3-11ea-968e-5ba7e32b75cd.jpg)
![Screenshot_2020-08-03-15-01-34-514_com example gowa_goaoverwhelminglywelcomesyou](https://user-images.githubusercontent.com/32892545/89174692-e8c79180-d5a3-11ea-901d-9d027addb583.jpg)

**Comment by ASarchna** [comment]
Great! Looks perfect now!
